name: Deploy production
on:
  push:
    tags:
      - v*.*.*

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.HOST_NAME }}
      DATABRICKS_TOKEN: ${{ secrets.HOST_TOKEN }}
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Install databricks cli
        uses: databricks/setup-cli@main
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true 
      - name: Deploy bundle to production
        run: |
          databricks bundle deploy --target prod
      - name: Run a job
        run: |
          databricks bundle run -t prod run_notebook
      - name: Summary
        run: |
          echo "Deployed successfully, target=prod"
          echo "Tag=${{ github.ref_name }}"
          echo "Commit SHA=${{ github.sha }}"