name: Drift Check Nightly
on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at  AM UTC
  workflow_dispatch:
jobs:
  drift-check:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.HOST_NAME }}
      DATABRICKS_TOKEN: ${{ secrets.HOST_TOKEN }}
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Install databricks cli
        uses: databricks/setup-cli@main
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true 
      - name: Bundle Validation
        run: |
          databricks bundle validate
      - name: Drift Checking
        run: |
          databricks bundle plan
      - name: Correct Drifting
        run: |
          databricks bundle deploy
      - name: Summary
        run: |
          databricks bundle summary